# Site
repository: sproogen/resume-theme
favicon: favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gediminas Šimavičius
title: Data Analyst
email: gediminas.simavicius@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Gedas-LT
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: gediminas-simavicius
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: profile_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  My journey started in <mark>physics</mark>, then I dived in <mark>marketing</mark> and now I decided to dwell in <mark>data science</mark> with all my knowledge from physics and advertising.

content:

  - title: Experience # Title for the section
    layout: text # Type of content section (list/text)
    content:
      - layout: left
        title: DELFI Lithuania
        sub_title: Data Analyst
        caption: November 2020 - Present
      - layout: top-middle
        title: Inspired UM
        sub_title: Digital Media Planner
        caption: September 2016 - November 2020
        
      - layout: top-middle
        sub_title: Digital Campaign Manager
        caption: April 2016 - August 2016
        
      - layout: top-right
        title: TV3 Lithuania
        sub_title: Online Sales Planner
        caption: February 2015 - March 2016
        
      - layout: top-right
        sub_title: Online Editor
        caption: May 2011 - January 2015
       
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Turing College
        caption: 2020 - Present
        sub_title: Data Science
        link: turingcollege.com
    
      - layout: left
        title: Vilnius University
        caption: 2010 - 2012
        sub_title: Master's Degree in Information Facility, Management of Information Systems
        
      - layout: left
        title: Vilnius University
        caption: 2006 - 2010
        sub_title: Bachelor's Degree in Physics, Computing Physics
         
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Volcanic Eruptions
        caption: My very first project from Turing college with EDA.
        link: github.com/Gedas-LT/turing-projects/blob/main/volcanos_eda.ipynb 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science and various fields of physics some of my other interests and hobbies are:
      - Cycling
      - Gaming
      - Reading

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
